<?php

$a = "concat";
$b = "enate";
$c = $a.$b;
print $c."<br>";
print strtoupper($c)."<br>";

$arr = [1, 2, 3, 4];
print implode("|", $arr)."<br>";
foreach ($arr as $elem){
    if($elem%2){
        print "odd<br>";
    }
    else{
        print "even<br>";
    }
}

$dict = ["key1" => "value1", "key2" => "value2"];
print $dict["key2"]."<br>";
$dict["key2"] = "new value";
print $dict["key2"]."<br>";

function test($arr){
    return $arr[rand(0, 3)];
}

print test($arr)."<br>";

class TestClass{
    public $aboba;

    function __construct($value){
        $aboba = $value;
    }

    function getaboba(){
        return $this->aboba;
    }

    function talk(){
        print "Hello, I am aboba)<br>";
    }

    function __destruct(){
        print "I am dying(<br>";
    }
}

class Child extends TestClass{
    public $ocupation;

    function __construct($value, $ocupation)
    {
        parent::__construct($value);
        $this->ocupation = $ocupation;
    }

    function talk()
    {
        parent::talk(); // TODO: Change the autogenerated stub
        print "I am a child)<br>";
    }

    function getocupation(){
        return $this->ocupation;
    }

    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
        print "I was just a child<br>";
    }
}

$aboba = new TestClass("Khrys");
$child = new Child("Shera", "dog");
$aboba->talk();
$child->talk();
print $child->getocupation()."<br>";
?>

